version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_pgdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alpha123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  my-go-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: alpha123
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: my_pgdb
      DB_SSL_MODE: disable
    ports:
      - "8081:8080"

volumes:
  postgres-data:
